### ISSUE TITLE
ByteArray.toByteString for numbers return empty string

### ISSUE THREAD

**Issue by Thykof** [massalabs/as#23]
In this PR https://github.com/massalabs/massa-as-sdk/pull/23 I try to create an Args class that handle the encoding and decoding of function call arguments.

The problem is that I can't make the current code work.

```typescript
const ADDR1 = 'A1Czd9sRp3mt2KU9QBEEZPsYxRq9TisMs1KnV4JYCe7Z4AAVinq';
const ADDR2 = 'A1cjz8wvMvShrBH5eqGYkuFGGncTNqszJc1BDKwR7oou8fpLD2E';

const ENCODED =
  '3A1Czd9sRp3mt2KU9QBEEZPsYxRq9TisMs1KnV4JYCe7Z4AAVinq3A1cjz8wvMvShrBH5eqGYkuFGGncTNqszJc1BDKwR7oou8fpLD2Ed';

describe('Args tests', () => {
  it('encode, old way', () => {
    const ownerAccount = new Address(ADDR1);
    const recipientAccount = new Address(ADDR2);
    const nbTokens = new Amount(100);
    const result = ownerAccount
      .toStringSegment()
      .concat(
        recipientAccount
          .toStringSegment()
          .concat(ByteArray.fromU64(nbTokens.value()).toByteString()),
      );
    expect(result).toBe(ENCODED); // broken
  });
  it('decode, old way', () => {
    const args = ENCODED;
    const ownerAddress = new Address();
    let offset = ownerAddress.fromStringSegment(args);

    const recipientAddress = new Address();
    offset = recipientAddress.fromStringSegment(args, offset);

    const amount = ByteArray.fromByteString(args.substr(offset, 8)).toU64();

    expect(ownerAddress._value).toBe(ADDR1);
    expect(recipientAddress._value).toBe(ADDR2);
    expect(amount.toString()).toBe('100'); // broken
  });
});
```

Because `ByteArray.fromU64` creates a Byte Array with value 1 and in `toByteString`, `String.fromCharCode(1);` returns an empty string according to this https://asecuritysite.com/coding/asc2

I might misunderstood something, could anyone help me on this please?

**Comment by peterjah** [comment]
Why don't you use helpers from Amount class?
``` amount.toStringSegment()```
instead of ```ByteArray.fromU64(nbTokens.value()).toByteString()```

And

```const amount = new Amount();```
  ```amount.fromStringSegment(_args, offset);```

  instead of
```const amount = ByteArray.fromByteString(args.substr(offset, 8)).toU64();```

**Comment by peterjah** [comment]
https://github.com/massalabs/as/blob/28024372b158c2ac4ff026d705169c0c795c1fe7/assembly/amount.ts#L142
it seems that the first byte of stringSegments of amounts is a length field. which is useless because the output is alwas u64 (8bytes length) 🤔

**Comment by peterjah** [comment]
i think a nice evolution of this would be to have a "type" field so you can decode the bitstream without knowing types in advance

**Comment by peterjah** [comment]
A nice evolution of this would be to have a custom preprocessor launched just before building. The equivalent of Macros in C/Cpp
it would allow to write function arguments as usual:

```
export function transferFrom(ownerAddress: Address, recipientAddress: Address, amount: Amount): string {
```
the preprocessor will automatically transform it to the following code:
``` 
export function transferFrom(args: string): string {
const ownerAddress = new Address();
let offset = ownerAddress.fromStringSegment(args);
const recipientAddress = new Address();
offset = recipientAddress.fromStringSegment(args, offset);
const amount = ByteArray.fromByteString(args.substr(offset, 8)).toU64();
```
We can facilltatte the detection of the code to replace by using a custom decorator on the func (@massa-args for example)

**Comment by gregLibert** [comment]
A couple of thoughs on this issue:
- I think that ByteArray object should be removed and replaced by [Args](https://github.com/massalabs/massa-as-sdk/issues/16).
- After discussing it with @Thykof and @peterjah , my feeeling is that the code is working but there a problem with .toBe in unit test.
- Having the Args object will make @peterjah previous proposal about a transformer simpler to implement.

**Comment by Thykof** [comment]
@gregLibert I am working on Args class and I need pieces of code of ByteArray class. So I can use ByteArray are copy paste the methods I need into Args, if we want to remove ByteArray class.
