### ISSUE TITLE
Fix 'generateEvent' import issue when using transformer

### ISSUE THREAD

**Issue by 0xSwapFeeder** [massalabs/as#238]
For the moment, we can't use manually the 'generateEvent' method from 'massa-as-sdk' in a smart contract if we are using the new protobuf transformer.

It seems to occur because the transformer it self generates a wrapper by adding a 'generateEvent' call in the 'massaExport' decorated functions and therefore it declares it instead of importing it from 'massa-as-sdk' which cause the double definition when imported in the contract.

Either we delete the automatic declaration and usage of 'generateEvent' in the wrappers or we do it dynamically only when it is not imported by the SC dev in the contract.

**Comment by 0xSwapFeeder** [comment]
@gregLibert I would like your thoughts on this one, wdyt ?

**Comment by gregLibert** [comment]
As it is done manualy, what is missing ?
FIY I finaly did that because the import of massa-as-sdk wasn't working as expected. But maybe it's fixed now. Did you try removing the manual injection of the generateEvent and replace it with the import of massa-as-sdk to see if it works ?

**Comment by 0xSwapFeeder** [comment]
While testing furthermore, I noticed that any external node module import in the smart contract (not only from 'as-sdk') are breakiing either the compilation or the transformer itself
