### ISSUE TITLE
as-transformer: fix compilation issues

### ISSUE THREAD

**Issue by 0xSwapFeeder** [massalabs/as#256]
At the moment there are several issues:
- compilation randomly crashes when using 'massaExport' decorator
- generated files by the transformer are being passed through the transformer
- transformer is passing on already transformed files because of the parse calls
- the transformer doesn't support full project mirroring (from 'assembly/contracts/*' to 'build/assembly/contracts/*'

For this last point, the resolving can be omitted by updating massa-sc-compiler '-r' option to not mirror the project but only sub directories within 'assembly/contracts/'

**Comment by 0xSwapFeeder** [comment]
Wdyt @gregLibert, @Ben-PH ?

**Comment by gregLibert** [comment]
> Wdyt @gregLibert, @Ben-Rey ?

I think this is something that we should discuss. can you organize a call on this as requested this morning during the daily ?
