### ISSUE TITLE
Implement massaExport transformer for 'export' statements.

### ISSUE THREAD

**Issue by 0xSwapFeeder** [massalabs/as#262]
To have a module like contract with exported functions in other files than the main file, we need to be abble to mark some export statements with '@massaExport' decorator to be able to transform them for exportation and also transform their call inside the file where they are exported.

**Comment by bilboquet** [comment]
@Ben-Rey 
:warning: I'm not sure I correctly understand the issue.

I guess it means that the transformer must not break this code
```as
function f1(): void {
  f2(…);
}

@massaExport
export function f2(…): void {
}
```
If I'm correct, this is supported: original `f2()` (before transformation) gets renamed both at it's declaration point and call sites.

**Comment by Ben-Rey** [comment]
I think the problem would be if f2 is in another file

**Comment by bilboquet** [comment]
#330 should solve this problem
