### ISSUE TITLE
Warning when building for simple project

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/as#285]
I have followed the quickstart and when I build I have the following error : 
```
Npm run build: compiler mismatch: std/portable included twice
```

It could be nice to remove all the logs that avoid seeing the compile error directly : 
```
> npx massa-as-compile

2 files to compile
compiler mismatch: std/portable included twice
Starting after parse hook.
Transforming source: assembly/contracts/main


Finished transforming source: assembly/contracts/main
finished after parse hook
Starting after parse hook.
Transforming source: assembly/contracts/run


Finished transforming source: assembly/contracts/run
finished after parse hook
contract to compile assembly/contracts/run.ts

contract to compile assembly/contracts/main.ts
```

**Comment by 0xSwapFeeder** [comment]
the "compiler mismatch" warning is not a compile error, it was there way before the as-transformer upgrade, however I can remove the logs from the transformer.
That's odd tho because all logs are made so that you can only see them in debug mode i'll investigate on that.

**Comment by AurelienFT** [comment]
Yes at least remove the debug log is ok

**Comment by JoeTheCookie217** [comment]
Any progress on this? It's pretty annoying when working with multiple contracts
