### ISSUE TITLE
nextSerializable<T> fails on classe with constructor that requires argements

### ISSUE THREAD

**Issue by pewulfman** [massalabs/as#334]
https://github.com/massalabs/as/blob/1ed2d3046e87616acaaf4d4b4291957240a2441a/packages/as-types/assembly/argument.ts#L566

When using `nextSerializable<T>()` if T has a constructor with required parameters, compilation fails with a confusing error.

This problem comes from instantiate being called without arguments and calling the constructor of T with the arguments provided.

From there, either this is voluntary that we instantiate a dummy object (since the value will be overridden anyway) and then it should be made clear that a class that implements Serializable needs a constructor with no parameters.

Or we can modify the signature of nextSerializable as `nextSerializable<T> (...args: any[])` and give those args to `instantiate<T>`

**Comment by peterjah** [comment]
its indeed a pain. as a workaround you can set default values in your constructor:
` 
 constructor(
    public tata: string = '',
    public titi: string = '',
    public toto: number = 0,
  ) {}
  `

**Comment by pewulfman** [comment]
yup, that's what we did. 
It is a bit annoying because then we can't type checker that we do provide parameters to the `new Class ()`, so I added a static method create for this and add the coding rules that we need to use this
