### ISSUE TITLE
Incorrect serialization of Array<u256>

### ISSUE THREAD

**Issue by sydhds** [massalabs/as#335]
Assembly script code:

```
export function arr0(): StaticArray<u8> {
    let arr: Array<u256> = new Array(2);
    arr[0] = u256.Zero;
    arr[1] = u256.Max;
    return new Args().add(arr).serialize();
}
```

Typescript code:

```
    let readData: IReadData = {
        maxGas: BigInt(10_000_000),
        targetAddress: scAddr,
        targetFunction: "arr0",
        parameter: new Args().serialize(),
    }
    const resp = await client.smartContracts().readSmartContract(readData);
    console.log("resp", resp);

    return new Args(resp.returnValue).nextArray(ArrayTypes.U256);
```

returns an offset error

**Comment by peterjah** [comment]
Looks like a bug :)
The use of Args is useless in this exemple, can you try to serialize/deserialize directly ?
replace
`return new Args().add(arr).serialize();` by `fixedSizeArrayToBytes(arr)`
and `return new Args(resp.returnValue).nextArray(ArrayTypes.U256);` by `return bytesToArray(resp.returnValue, ArrayTypes.U256)`

it will help to locate the potential bug.

Another thing, can you provide the version of @massalabs/as-types and @massalabs/massa-web3 ?

**Comment by sydhds** [comment]
fixedSizeArrayToBytes is buggy with bignum types (like u256), I'm working on a fix right now :)
