### ISSUE TITLE
Upgrade assemblyscript + as-pect

### ISSUE THREAD

**Issue by peterjah** [massalabs/as#338]
we are at least 2 major version behind the latest AS version.
Upgrade will allow us to get back the coverage of as code...

**Comment by Ben-Rey** [comment]
I think we need to wait for https://github.com/as-pect/visitor-as/pull/44 and https://github.com/as-pect/as-covers/pull/13 to be able to make the coverage works

**Comment by AurelienFT** [comment]
@Ben-Rey as-pect is unmaintained I propose that we host a fork where we include the changes of the PR mentioned above.

The update of assemblyscript will impact all the tooling and should be thinking more globally, no ?

**Comment by Ben-Rey** [comment]
> @Ben-Rey as-pect is unmaintained I propose that we host a fork where we include the changes of the PR mentioned above.
> 
> The update of assemblyscript will impact all the tooling and should be thinking more globally, no ?

You're right, I can take care of that.
