### ISSUE TITLE
Add bytes <> string conversion

### ISSUE THREAD

**Issue by Trottoir** [massalabs/as#47]
Add a way to convert  StaticArray<u8> to string and vice-versa

**Comment by Thykof** [comment]
One on the function you want already exists in mass-as-sdk https://github.com/massalabs/massa-as-sdk/blob/4a8be29e13952096a117e4a21a272fe0b45d55f8/assembly/std/index.ts#L327

**Comment by damip** [comment]
And the second one is just below: https://github.com/massalabs/massa-as-sdk/blob/4a8be29e13952096a117e4a21a272fe0b45d55f8/assembly/std/index.ts#L338
