### ISSUE TITLE
Create a Good readme - AS

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/as#68]
**Prerequisite**
- https://github.com/massalabs/massa-as-sdk/issues/130

**The context:**

AS is a monorepo containing separate packages that provide functionalities for AS. It is poor and does not explain what each of the packages are meant for. 
Very good starting reference for readme is massa-web3 one: https://github.com/massalabs/massa-web3

**The need**
- Readme should have a better onboarding for SC-devs to using our AS libraries and tools. 
- It should also contain descriptions of components, as well as how we handle the releases (short description). 

**How-to:**
TypeDocs can generate the documentation of our tooling packages.
We will have to maintain the Readme manually and add a link to the generated html documentation.
Therefore, with each new feature and important improvements, the requirement will be updating the typedoc in the source code of the repo.

**Tech details:**
- [x] set the lint configuration
- [x] fix all typedoc
- [x] deploy the html type-doc
- [x] write the readme for as-transformer

**Comment by 0xMazout** [comment]
For me the readme transformer is okay, needs to be improved on the next phases to have relevant docs but right now it looks good
