### ISSUE TITLE
Create a good ReadMe AS-TYPES

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/as#69]
**Prerequisite**
- https://github.com/massalabs/as/issues/68

**The context:**

As-types has a poor [readme](https://github.com/massalabs/as/tree/main/packages/as-types). 
Very good starting reference for readme is massa-web3 one: https://github.com/massalabs/massa-web3

**The need**

Readme should explain all classes, and best practices that involve the usage of as-types. 
- [ ] This will be done by adding in the readme a link to the generate typedoc documentation website

**How-to:**
TypeDocs can generate the documentation of our packages. 
Therefore, with each new feature and improvements, the requirement will be updating the typedoc of the source code of the repo.

**Tech details:**

**Comment by longgamma-massa** [comment]
We can cross-reference with AS repo if necessary, but it should be a standalone readme for as-types package details

**Comment by 0xMazout** [comment]
Doc is deployed on this : https://github.com/massalabs/as/issues/68

**Comment by 0xMazout** [comment]
Link to the documentation : https://as-types.docs.massa.net/

We can review the readme.

The link to the doc in the readme os as types was added in the https://github.com/massalabs/as/issues/68
