### ISSUE TITLE
Create a good ReadMe AS-PROBA

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/as#70]
**Prerequisite**
- https://github.com/massalabs/as/issues/68

**The context:**

As-proba has a poor [readme](https://github.com/massalabs/as/tree/main/packages/as-proba). 
Very good starting reference for readme is massa-web3 one: https://github.com/massalabs/massa-web3

**The need**

Readme should explain all mathematic and probabilistic classes and functions, and best practices that involve the usage of those.

**How-to:**
TypeDocs can generate the documentation of our packages. The readme will contain a link to the generated documentation
Therefore, with each new feature an improvements, the requirement will be updating the typedoc of the source code of the repo.

**Tech details:**

**Comment by 0xMazout** [comment]
Doc is deployed on this : https://github.com/massalabs/as/issues/68
