### ISSUE TITLE
Create an assemblyscript transfomer to do Args deserialization of argument

### ISSUE THREAD

**Issue by Thykof** [massalabs/as#77]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

- add a new transformer
- define and create the function signature that the transformer will match

for example we would like to transform:
```typescript
export function greetings(arguments(firstArg: string, secondArg: i32)) {...}
```

into:
```typescript
export function greetings(_args: StaticArray<u8>) {
   const args = new Args(_args);
   const firstArg: string = args.nextString().expect('argument 1 is invalid');
   const secondArg: i32 = args.nextI32().expect('argument 2 is invalid');
  ...
}
```

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by peterjah** [comment]
i propose to use a pattern to define function which will be processed by the transormer,
by instance:
`##ser_greetings(firstArg: string, secondArg: i32)`
would mean that this function has to be transformed for its args to be deserialized

**Comment by Thykof** [comment]
It could be great to find a pattern that the IDE doesn't complains
maybe with decorator like as-serde: https://github.com/ask-lang/serde-as/tree/main/packages/as-serde

**Comment by longgamma-massa** [comment]
I wanted us to do a similar thing for serialization, as a precompilation thing. Maybe we should discuss this idea a bit more @peterjah @Thykof

**Comment by Thykof** [comment]
yes we should do a similar thing for serialization of function arguments, function return value and storage value, but let's start with de-serialize function argument.

**Comment by Ben-Rey** [comment]
@gregLibert is this still an issue now that we are working on protobuf?
