### ISSUE TITLE
Add new types for Args class

### ISSUE THREAD

**Issue by jimmylies** [massalabs/as#80]
### Context
We would like new types in the Args class to use them in our smart contracts.

The types we need are:
- done u64 - single integer (already in as-types)

Dusa project is requesting the following types:
- [x] #93
- [x] #89
  - [x] and https://github.com/massalabs/massa-as-sdk/pull/145
- [x] Address[ ] - array of addresses: https://github.com/massalabs/massa-as-sdk/issues/150

### How-to
- check string length for Address
- Unit-testing requried

**Comment by Thykof** [comment]
I have make this issue a meta issue, it means we are referencing other issues in this one.

I have created an issue to be able to serialize any object (thanks to a Serializable interface working with `Args`)

To be technically clarified: how to serialize arrays?

**Comment by Thykof** [comment]
Technical clarification on how to serialize array: see implementation here https://github.com/massalabs/massa-as-sdk/pull/145/files
