### ISSUE TITLE
Implement Serializable in Amount, Currency

### ISSUE THREAD

**Issue by Thykof** [massalabs/as#91]
_Originally posted by @Thykof in https://github.com/massalabs/as/pull/90#discussion_r1086844997_
   
## How to
for as-types Amount and Currency classes 
- [ ] deprecate to/from Args methods
- [ ] implement Serializable interface
- [ ] add serialization/deserialization unit tests

**Comment by Ben-Rey** [comment]
This was done here https://github.com/massalabs/as/pull/212
