### ISSUE TITLE
Deprecate Valider

### ISSUE THREAD

**Issue by Thykof** [massalabs/as#92]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

Coming from https://github.com/massalabs/massa-as-sdk/pull/145#discussion_r1089184832

The `Valider` interface is no longer useful.

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

- deprecate it

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Ben-Rey** [comment]
Duplicate with https://github.com/massalabs/as/issues/186
