### ISSUE TITLE
Create a SafeMath Library ( Addition & Substraction)

### ISSUE THREAD

**Issue by Trottoir** [massalabs/as#98]
## Context
Math operation on computer could go wrong because of the maximum value that a number can take.

Example: if you add to number with each value is MAX_VALUE, you can't have a correct result, this is called an overflow (it goes beyong). Same thing appear when substracting bellow the minimum value.
(MAX_VALUE being the maximum value a number can take in a computer, because its not infinite like in real math)

In ethereum, OpenZeppelin developed a bunch of function to handle this: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeMath.sol

## How to
We need to create a library (or better find an existing one) that handles overflow & underflow on : 

- [x] Addition 
- [x] Subtraction
- [x] multiplication
- [x] division
- [ ] modulo 

Also write unit tests.

These functions must not `assert` but rather return a `Result`

This existing library is WIP https://github.com/MaxGraey/as-bignum/tree/master/assembly/integer/safe

Existing SafeMath library of another blockchain that uses a custom 'Result'-like return type (SafeInteger): https://github.com/koinos/koinos-sdk-as/blob/master/assembly/util/safeMath.ts

**Comment by gregLibert** [comment]
@Thykof What does safemath means for division? is 1/3 safe ?

**Comment by Thykof** [comment]
a safe division will check if denominator is not 0, return `new Result(0, 'division by zero')` if yes, return `new Result(a / b)` otherwise

**Comment by gregLibert** [comment]
> a safe division will check if denominator is not 0, return `new Result(0, 'division by zero')` if yes, return `new Result(a / b)` otherwise

So it doesn't care that the result is not a decimal? Interesting...

**Comment by Thykof** [comment]
input are integers, output also
